### ISSUE TITLE
Cannot resolve FontAwesome

### ISSUE THREAD

**Issue by Divala** [zTrap/Android-Iconics-Kt#1]
I have added both core and views but am getting cannot resolve FontAwesome. What am I missing?

**Comment by Divala** [comment]
connectionTv.startIcon {
            icon(FontAwesome.Icon.faw_android)
            color(Color.GREEN)
        }

**Comment by zTrap** [comment]
This font you can get with this dependency: 
`implementation 'com.mikepenz:fontawesome-typeface:5.0.13.0@aar'`

All available fonts you can find [here](https://github.com/mikepenz/Android-Iconics#2-choose-your-desired-fonts)

**Comment by Divala** [comment]
Thanks but its just blank no icon is displayed

**Comment by zTrap** [comment]
@Divala I guess, you forget to define size of icon and icon have been setted with 0px size
